### PR TITLE
bump build number (v2.5.1)

### PR DESCRIPTION
**Pull request by jGaboardi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jGaboardi** [comment]
@conda-forge-admin, please rerender

**Comment by jGaboardi** [comment]
cc: @weikang9009 @knaaptime

**Comment by martinfleis** [comment]
@jGaboardi what is the purpose of this PR?

**Comment by jGaboardi** [comment]
> @jGaboardi what is the purpose of this PR?

This fixes the similar problem `esda` is having to what happened in `giddy` as @weikang9009 realized --> https://github.com/pysal/giddy/issues/212#issuecomment-2092083657. Seems that bumping the build and rerendering will help resolve. Is there harm in trying this (even though the `setupuptools-scm` is already in here)?

**Comment by martinfleis** [comment]
No harm, go ahead. It just looks from the diff that it does virtually nothing.

**Comment by jGaboardi** [comment]
@martinfleis 

I'm wondering if the version discrepancy may also be caused by the slight difference in what is happening [at this install step](https://github.com/conda-forge/esda-feedstock/pull/26/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR14). Wanted to see how that affects the result. Otherwise, seems like it must be something differently. in the update/newly created infrastructure files.

**Comment by jGaboardi** [comment]
At any rate, got time for a review/merge?

**Review by martinfleis — APPROVED** [review]
I don't think the additional args will hurt but I also don't think they matter. lgtm

**Pull request merged**
